### PR TITLE
introduction

### PR DESCRIPTION
**Pull request by seurcoding**
Hello Mr. david kindly reviews this , am going to pull more

### CODE REVIEW

**Review by davidinmichael — COMMENTED** [review]
I'm glad that you took out your time to do your findings, this good.
Weldone.

But then, you mentioned that 'C' is a lowlevel programming language and that is why we started off with it, tell us why it is a low level programming language.

**Comment by seurcoding** [comment]
c- it uses human like languange languange
also compiler in c convert source code into mashine code 
which can be direct accessed to hardware and lack of abstraction

**Review by davidinmichael — COMMENTED** [review]
TASKS/Task 001.c has been done correctly.
I'm impressed by the amount of work. Weldone.

**Comment by seurcoding** [comment]
Thanks, sir

**Review by davidinmichael — COMMENTED** [review]
You did a great job in your tasks, weldone.

**Pull request closed without merging**
