### PR TITLE
Solution to Task - Dukeson

### PR DESCRIPTION
**Pull request by Sampul-CodeMine**
This is a solution to the task you gave as an assignment to Introduction and Fundamentals of C programming Language.
Kindly review.

Thank you.

### CODE REVIEW

**Review by davidinmichael — COMMENTED** [review]
Wel-done for the attempts, I'm really impressed.
TASKS/Task 001.c - I love how you used the continue Statement for it, means you understand it better.

TASKS/Task 002.c - What if the user enters a letter by mistake, what would be the error message?

TASKS/Task 003.c - Your work here shows, you understand the Ternary Operator.

TASKS/Task 004.c - Very good.

Very good job here
Wel-done

**Review by Sampul-CodeMine — COMMENTED** [review]
Correction to task 2 - Dukeson.

**Comment by Sampul-CodeMine** [comment]
Correction to task 2 - Dukeson.

**Comment by Sampul-CodeMine** [comment]
Tasks correction

**Review by davidinmichael — COMMENTED** [review]
You decided to smash TASKS/Task 002.c
This is good I must say, it makes me happy seeing this.

**Comment by Sampul-CodeMine** [comment]
Thank you very much for the opportunity. God bless you for the hard work of trying to help others.

**Comment by Sampul-CodeMine** [comment]
Good day Mentor David. Kindly find the solutions to the tasks.

**Pull request closed without merging**
