### PR TITLE
Solutions to the tasks

### PR DESCRIPTION
**Pull request by DevOse**

### CODE REVIEW

**Review by davidinmichael — COMMENTED** [review]
This is great, I'm totally Impressed by the work.

TASKS/Task 003.c - in the printf, the task required that you print the number entered by the user in the place of 'userInput'.

**Comment by DevOse** [comment]
> This is great, I'm totally Impressed by the work.
> 
> TASKS/Task 003.c - in the printf, the task required that you print the number entered by the user in the place of 'userInput'.

**Review by davidinmichael — COMMENTED** [review]
Looking back at the changes you made in TASKS/Task 003.c, it's great, shows you understand what you're doing.
Weldone.

**Comment by DevOse** [comment]
> Looking back at the changes you made in TASKS/Task 003.c, it's great, shows you understand what you're doing.
> Weldone.

Thank you.

**Review by davidinmichael — COMMENTED** [review]
TASKS/Task 002.c
Consider using an else if clause, so the else clause could for the error message.

**Pull request closed without merging**
